#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

find_args=(-type f -not -path './build/*' \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.cc' \) -print0)

find tea teapot "${find_args[@]}" | xargs -0 clang-format --dry-run -Werror
find tea teapot "${find_args[@]}" | xargs -0 cpplint --quiet
