name: GP6 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear cache
        run: |
          cd /opt
          find . -maxdepth 1 -mindepth 1 '!' -path ./containerd '!' -path ./actionarchivecache '!' -path ./runner '!' -path ./runner-cache -exec rm -rf '{}' ';'

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            bison \
            ccache \
            cmake \
            curl \
            flex \
            llvm \
            inetutils-ping \
            krb5-kdc \
            krb5-admin-server \
            libapr1-dev \
            libbz2-dev \
            libcurl4-gnutls-dev \
            libevent-dev \
            libkrb5-dev \
            libpam-dev \
            libperl-dev \
            libreadline-dev \
            libssl-dev \
            libxerces-c-dev \
            libxml2-dev \
            libyaml-dev \
            libzstd-dev \
            locales \
            net-tools \
            ninja-build \
            openssh-client \
            openssh-server \
            openssl \
            pkg-config \
            python3-dev \
            python3-pip \
            python3-psycopg2 \
            python3-psutil \
            python3-yaml \
            zlib1g-dev
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          which gcc-13
          which g++-13

      - name: Prepare directory for installation
        run: |
          mkdir -p $HOME/local

      - name: Build and install Greenplum 6
        run: |
          git clone https://github.com/arenadata/gpdb.git
          cd gpdb
          git checkout 6.29.1_arenadata68
          git submodule update --init
          ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=$HOME/local/gpdb
          make -j8
          make -j8 install
          rm -rf gpdb

      - name: Build and install Arrow 15
        run: |
          mkdir build
          git clone https://github.com/apache/arrow.git
          cd arrow
          git checkout maint-15.0.2
          git apply ../vendor/arrow/fix_c-ares_url.patch
          ./cpp/thirdparty/download_dependencies.sh ../build/arrow-thirdparty
          mkdir cpp/build
          cd cpp/build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$HOME/local \
            -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13 \
            -DARROW_BUILD_STATIC=ON -DARROW_BUILD_SHARED=OFF \
            -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_NO_DEPRECTATED_API=ON \
            -DARROW_LLVM_USE_SHARED=OFF -DARROW_FILESYSTEM=ON -DARROW_PARQUET=ON \
            -DARROW_S3=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_LZ4=ON -DARROW_WITH_ZLIB=ON -DARROW_WITH_ZSTD=ON \
            -DARROW_IPC=ON -DARROW_CSV=ON -DARROW_WITH_RAPIDJSON=ON \
            -DARROW_GANDIVA=ON -DARROW_COMPUTE=ON ..
          make -j8
          make -j8 install
          rm -rf arrow

      - name: Build and install gprc
        run: |
          git clone https://github.com/grpc/grpc.git
          cd grpc
          git checkout v1.62.3
          git submodule update --init --single-branch --depth 1
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$HOME/local \
            -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13 \
            -DgRPC_BUILD_SHARED_LIBS=OFF -DgRPC_BUILD_STATIC_LIBS=ON \
            -DgRPC_BUILD_TESTS=OFF -DgRPC_BUILD_EXAMPLES=OFF \
            -DgRPC_BUILD_CSHARP_EXT=OFF -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF \
            -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
            -DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF -DgRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF \
            -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF ..
          make -j8
          make -j8 install
          rm -rf grpc

      - name: Build Tea
        run: |
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DTEA_DEPS_PATH=$HOME/local \
            -DGreenplum_ROOT=$HOME/local/gpdb -DCMAKE_PREFIX_PATH=$HOME/local \
            -DCMAKE_C_COMPILER=gcc-13 -DCMAKE_CXX_COMPILER=g++-13 ..
          ninja
          ninja install
